name: Release Drafter

on:
  push:
    branches:
      - main
  # The pull_request event is required for the autolabeler feature.
  # If you want the autolabeler to work with PRs from forks, use pull_request_target.
  pull_request:
    types: [opened, synchronize]
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # (Optional) If you are using GitHub Enterprise, set the GHE_HOST
      # - name: Set GHE_HOST
      #   run: |
      #     echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      # This step runs the Release Drafter action.
      - uses: release-drafter/release-drafter@v6
        # (Optional) You can specify a different configuration file name.
        # with:
        #   config-name: my-custom-config.yml
        #   disable-autolabeler: true # Set to true to disable the autolabeler feature
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
